### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by haroldolivieri** [homoluctus/slatify#12]
My workflow is failing at slatify step with an `ECONNREFUSED`  error.
Looks like it is a docker network error.

```
##[group]Run homoluctus/slatify@releases/v1
with:
  type: Success
  job_name: :robot_face: *PR opened*
  channel: #channel:
  url: ***
  username: Github Actions
  icon_emoji: github
env:
  JAVA_HOME: /opt/hostedtoolcache/Java/12.0.2/x64
  JAVA_HOME_12.0.2_x64: /opt/hostedtoolcache/Java/12.0.2/x64
  FLUTTER_HOME: /opt/hostedtoolcache/flutter/1.9.1-hotfix.2-stable/x64
##[endgroup]
Error: A request error occurred: connect ECONNREFUSED 127.0.0.1:80
    at Object.requestErrorWithOriginal (/home/runner/work/_actions/homoluctus/slatify/releases/v1/node_modules/@slack/webhook/dist/errors.js:25:33)
    at Slack.send (/home/runner/work/_actions/homoluctus/slatify/releases/v1/node_modules/@slack/webhook/dist/IncomingWebhook.js:54:32)
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  code: 'slack_webhook_request_error',
  original: Error: connect ECONNREFUSED 127.0.0.1:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 80,
    config: {
      adapter: [Function: httpAdapter],
      transformRequest: [Object],
      transformResponse: [Object],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      baseURL: '***',
      httpAgent: undefined,
      httpsAgent: undefined,
      maxRedirects: 0,
      proxy: false,
      url: '***/***',
      data: '{"username":"Github ' +
        'Actions","icon_emoji":"github","channel":"#channel:","text":":white_check_mark: ' +
        'GitHub Actions ' +
        'Success","attachments":[{"color":"#2cbe4e","blocks":[{"type":"section","fields":[{"type":"mrkdwn","text":"*repository*\\n<https://github.com/SuaMusica/OneApp|SuaMusica/OneApp>"},{"type":"mrkdwn","text":"*ref*\\nrefs/pull/93/merge"},{"type":"mrkdwn","text":"*event ' +
        'name*\\npull_request"},{"type":"mrkdwn","text":"*workflow*\\n<https://github.com/SuaMusica/OneApp/commit/ff3ff24bbd005ec97b7eabad86997b8e48feb115/checks|PR ' +
        'opened>"}],"text":{"type":"mrkdwn","text":":robot_face: *PR ' +
        'opened*"}}]}],"unfurl_links":true}'
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 625,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'POST ' +
        '***/*** ' +
        'HTTP/1.1\r' +
        '\nAccept: application/json, text/plain, */*\r' +
        '\nContent-Type: application/json;charset=utf-8\r' +
        '\nUser-Agent: @slack:webhook/5.0.1 node/12.4.0 linux/5.0.0-1016-azure\r' +
        '\nContent-Length: 625\r' +
        '\nHost: localhost\r' +
        '\nConnection: close\r' +
        '\n\r' +
        '\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      path: '***/***',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      [Symbol(isCorked)]: false,
      [Symbol(outHeadersKey)]: [Object: null prototype]
    },
    response: undefined
  }
}
##[error]A request error occurred: connect ECONNREFUSED 127.0.0.1:80
##[error]Node run failed with exit code 1
```

**Comment by homoluctus** [comment]
Hi @haroldolivieri 

Your workflow failed because the value of "channel" parameter is invalid.
The value of "channel" parameter is "#channel:".
Therefore, if you remove ":" from "#channel:", your workflow will work properly.

**Comment by haroldolivieri** [comment]
I've fixed the channel name but the issue persists.

```
Run homoluctus/slatify@releases/v1
  with:
    type: Success
    job_name: :robot_face: *PR opened*
    channel: #oneapp
    url: ***
    username: Github Actions
    icon_emoji: github
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java/12.0.2/x64
    JAVA_HOME_12.0.2_x64: /opt/hostedtoolcache/Java/12.0.2/x64
    FLUTTER_HOME: /opt/hostedtoolcache/flutter/1.9.1-hotfix.2-stable/x64
Error: A request error occurred: connect ECONNREFUSED 127.0.0.1:80
    at Object.requestErrorWithOriginal (/home/runner/work/_actions/homoluctus/slatify/releases/v1/node_modules/@slack/webhook/dist/errors.js:25:33)
    at Slack.send (/home/runner/work/_actions/homoluctus/slatify/releases/v1/node_modules/@slack/webhook/dist/IncomingWebhook.js:54:32)
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  code: 'slack_webhook_request_error',
  original: Error: connect ECONNREFUSED 127.0.0.1:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
```

**Comment by homoluctus** [comment]
Please confirm slack incoming webhook url and channel is correct.
If possible, please show me your workflows yaml file.
