### ISSUE TITLE
Build Process Documentation

### ISSUE THREAD

**Issue by samdeane** [homoluctus/slatify#63]
Could you document the build process a bit?

I'm trying to tweak the formatting, but am not sure how to recreate `dist/index.js` (js/ts is a bit out of my comfort zone).

When I do `npm run build` I'm getting errors:

```
~/Projects/slatify> npm run build                                                                                          (master)

> container-toolkit-template@0.0.0 build /Users/developer/Projects/slatify
> ncc build src/index.ts

ncc: Version 0.20.5
ncc: Compiling file index.js
ncc: Using typescript@3.7.5 (local user-provided)
Error: [tsl] ERROR in /Users/developer/Projects/slatify/src/slack.ts(91,41)
      TS2339: Property 'repos' does not exist on type 'GitHub'.
    at evalmachine.<anonymous>:1:1483065
    at eval (eval at create (evalmachine.<anonymous>:1:273347), <anonymous>:13:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I guess I've got a bad dependency or the wrong version of @actions/github?

**Comment by homoluctus** [comment]
@samdeane 

Have you installed ***dependencies*** not only devDependencies ?

The build procedure ↓

## 1. Install dependencies

```
npm install
```

## 2. Compile

```
npm run build
```

### Compile Output

ex)

```
> container-toolkit-template@0.0.0 build /Projects/slatify
> ncc build src/index.ts

ncc: Version 0.20.5
ncc: Compiling file index.js
ncc: Using typescript@3.7.5 (local user-provided)
523kB  dist/index.js
523kB  [2585ms] - ncc 0.20.5
```

**Comment by samdeane** [comment]
Thanks for getting back to me!

I have indeed run `npm install` first.

I tried to reset everything as much as possible, including removing the lock file, and here's what I get:

```
~/Projects/slatify> rm package-lock.json && rm -rf node_modules &&  npm install && npm run build                           (master)
npm WARN deprecated tslint@6.0.0: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

> fsevents@1.2.11 install /Users/developer/Projects/slatify/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm notice created a lockfile as package-lock.json. You should commit this file.
added 616 packages from 467 contributors and audited 897236 packages in 12.706s
found 0 vulnerabilities


> container-toolkit-template@0.0.0 build /Users/developer/Projects/slatify
> ncc build src/index.ts

ncc: Version 0.20.5
ncc: Compiling file index.js
ncc: Using typescript@3.7.5 (local user-provided)
Error: [tsl] ERROR in /Users/developer/Projects/slatify/src/slack.ts(95,41)
      TS2339: Property 'repos' does not exist on type 'GitHub'.
    at evalmachine.<anonymous>:1:1483065
    at eval (eval at create (evalmachine.<anonymous>:1:273347), <anonymous>:13:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! container-toolkit-template@0.0.0 build: `ncc build src/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the container-toolkit-template@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/developer/.npm/_logs/2020-02-07T10_27_36_828Z-debug.log
```

Is it possible that I've picked up too new a version of one of the dependencies? Should you maybe check in your lock file?

**Comment by suguru-yazawa** [comment]
@samdeane 

I ran the same command and got the same result.
The reason for failure is written [here](https://github.com/actions/toolkit/issues/333).

I'll fix this bug.

Thanks for the great feedback.

**Comment by homoluctus** [comment]
@samdeane 

I ran the same command and got the same result.
The reason for failure is written [here](https://github.com/actions/toolkit/issues/333).

I'll fix this bug.

Thanks for the great feedback.

**Comment by homoluctus** [comment]
I fixed this bug.
Now you can build.

**Comment by samdeane** [comment]
I can confirm it's working for me now. 
Thanks!

> 1. Install dependencies
>
> npm install
> 2. Compile
> 
> npm run build

Might be worth adding that to the Contribute section of the read me?

**Comment by homoluctus** [comment]
OK, I'll add build process to the Contribution section.
Thanks @samdeane .
